### ISSUE TITLE
ERROR    -  Error reading page '[INSERT_NOTEBOOK_TITLE].ipynb': 'state'

### ISSUE THREAD

**Issue by mrdbourke** [danielfrg/mkdocs-jupyter#73]
I'm not sure what's going on when converting a notebook I've been working on.

You can see the original notebook here: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/03_pytorch_computer_vision.ipynb 

The error I'm getting is: 
```
ERROR    -  Error reading page '03_pytorch_computer_vision.ipynb': 'state'
```

The full traceback is:

```
ERROR    -  Error reading page '03_pytorch_computer_vision.ipynb': 'state'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs/__main__.py", line [20](https://github.com/mrdbourke/pytorch-deep-learning/runs/5670248420?check_suite_focus=true#step:8:20)8, in gh_deploy_command
    build.build(cfg, dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs_jupyter/plugin.py", line 94, in new_render
    body = convert.nb2html(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs_jupyter/nbconvert2.py", line 105, in nb2html
    content, resources = exporter.from_filename(nb_path)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 190, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 208, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbconvert/exporters/html.py", line [21](https://github.com/mrdbourke/pytorch-deep-learning/runs/5670248420?check_suite_focus=true#step:8:21)0, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 392, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/jinja2/environment.py", line 9[25](https://github.com/mrdbourke/pytorch-deep-learning/runs/5670248420?check_suite_focus=true#step:8:25), in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs_jupyter/templates/mkdocs_html/notebook.html.j2", line 78, in top-level template code
    {%- set vars = {"cell_id": 0 } -%}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/lab/index.html.j2", line 3, in top-level template code
    {% from 'jupyter_widgets.html.j2' import jupyter_widgets %}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/lab/base.html.j2", line [26](https://github.com/mrdbourke/pytorch-deep-learning/runs/5670248420?check_suite_focus=true#step:8:26)0, in top-level template code
    {% set div_id = uuid4() %}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/base/display_priority.j2", line 1, in top-level template code
    {%- extends 'base/null.j2' -%}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/base/null.j2", line 26, in top-level template code
    {%- block body -%}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/base/null.j2", line [29](https://github.com/mrdbourke/pytorch-deep-learning/runs/5670248420?check_suite_focus=true#step:8:29), in block 'body'
    {%- block body_loop -%}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/base/null.j2", line [31](https://github.com/mrdbourke/pytorch-deep-learning/runs/5670248420?check_suite_focus=true#step:8:31), in block 'body_loop'
    {%- block any_cell scoped -%}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/base/null.j2", line [34](https://github.com/mrdbourke/pytorch-deep-learning/runs/5670248420?check_suite_focus=true#step:8:34), in block 'any_cell'
    {%- block codecell scoped -%}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs_jupyter/templates/mkdocs_html/notebook.html.j2", line 119, in block 'codecell'
    {{ super() }}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/lab/base.html.j2", line 12, in block 'codecell'
    {{ super() }}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/base/null.j2", line 44, in block 'codecell'
    {%- block output_group -%}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/lab/base.html.j2", line [38](https://github.com/mrdbourke/pytorch-deep-learning/runs/5670248420?check_suite_focus=true#step:8:38), in block 'output_group'
    {{ super() }}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/base/null.j2", line 48, in block 'output_group'
    {%- block outputs scoped -%}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/lab/base.html.j2", line [44](https://github.com/mrdbourke/pytorch-deep-learning/runs/5670248420?check_suite_focus=true#step:8:44), in block 'outputs'
    {{ super() }}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/base/null.j2", line [50](https://github.com/mrdbourke/pytorch-deep-learning/runs/5670248420?check_suite_focus=true#step:8:50), in block 'outputs'
    {%- block output scoped -%}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/lab/base.html.j2", line 87, in block 'output'
    {{ super() }}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/base/null.j2", line 67, in block 'output'
    {%- block display_data scoped -%}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/base/null.j2", line 68, in block 'display_data'
    {%- block data_priority scoped -%}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/lab/base.html.j2", line 115, in block 'data_priority'
    {{ super() }}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/share/jupyter/nbconvert/templates/base/display_priority.j2", line 7, in block 'data_priority'
    {%- for type in output.data | filter_data_type -%}
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbconvert/filters/widgetsdatatypefilter.py", line [56](https://github.com/mrdbourke/pytorch-deep-learning/runs/5670248420?check_suite_focus=true#step:8:56), in __call__
    metadata['widgets'][WIDGET_STATE_MIMETYPE]['state'] if
KeyError: 'state'
Error: Process completed with exit code 1.
```

I'm not quite sure where to even start with this one.

I'm going to be stepping back through the error.

But I've tried several things with the existing notebook:
* Rerunning the code cells + re-commiting
* Starting a *fresh* notebook and copying the code/markdown into the new notebook manually, cell by cell, error remains

I don't think I've done anything different to other notebooks I've worked on.

Yet this error remains.

You can see the GitHub Action I'm using to do the conversion here: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/.github/workflows/make_docs.yml

Please forgive me if this is the wrong repo to be posting this issue.

**Comment by mrdbourke** [comment]
Fixed this.

Turns out it was some weird way that Google Colab saved Jupyter Cells...

If you install a library in Google Colab and have to restart the runtime, then save the updated notebook, I feel like that's what causes it.

Though I didn't find conclusively what happened... 

To fix it I manually copied every cell from one notebook to a *new* notebook via Jupyter Lab on local host (not Google Colab).
